export type { Database, Json } from './database'
import type { Database } from './database'

type Tables = Database['public']['Tables']

// Row types
export type School = Tables['schools']['Row']
export type Term = Tables['terms']['Row']
export type BellSchedule = Tables['bell_schedules']['Row']
export type PeriodSlot = Tables['period_slots']['Row']
export type Room = Tables['rooms']['Row']
export type Teacher = Tables['teachers']['Row']
export type Subject = Tables['subjects']['Row']
export type Grade = Tables['grades']['Row']
export type Section = Tables['sections']['Row']
export type TeacherSubject = Tables['teacher_subjects']['Row']
export type SectionSubject = Tables['section_subjects']['Row']
export type FixedPeriod = Tables['fixed_periods']['Row']
export type CombinedClass = Tables['combined_classes']['Row']
export type CombinedClassSection = Tables['combined_class_sections']['Row']
export type ElectiveBlock = Tables['elective_blocks']['Row']
export type ElectiveOffering = Tables['elective_offerings']['Row']
export type ElectiveEnrollment = Tables['elective_enrollments']['Row']
export type Timetable = Tables['timetables']['Row']
export type TimetableSlot = Tables['timetable_slots']['Row']
export type TeacherAbsence = Tables['teacher_absences']['Row']
export type SubstitutionRequest = Tables['substitution_requests']['Row']
export type SubstitutionAssignment = Tables['substitution_assignments']['Row']
export type PeriodUnavailability = Tables['period_unavailabilities']['Row']
export type AdminEvent = Tables['admin_events']['Row']
export type AdminEventSection = Tables['admin_event_sections']['Row']
export type Notification = Tables['notifications']['Row']
export type PushSubscription = Tables['push_subscriptions']['Row']
export type TimetableEdit = Tables['timetable_edits']['Row']
export type TimetableSnapshot = Tables['timetable_snapshots']['Row']
export type ShareLink = Tables['share_links']['Row']
export type Holiday = Tables['holidays']['Row']

// Insert types
export type SchoolInsert = Tables['schools']['Insert']
export type TermInsert = Tables['terms']['Insert']
export type BellScheduleInsert = Tables['bell_schedules']['Insert']
export type PeriodSlotInsert = Tables['period_slots']['Insert']
export type RoomInsert = Tables['rooms']['Insert']
export type TeacherInsert = Tables['teachers']['Insert']
export type SubjectInsert = Tables['subjects']['Insert']
export type GradeInsert = Tables['grades']['Insert']
export type SectionInsert = Tables['sections']['Insert']
export type TimetableSlotInsert = Tables['timetable_slots']['Insert']
export type TimetableInsert = Tables['timetables']['Insert']
export type NotificationInsert = Tables['notifications']['Insert']

// Update types
export type TeacherUpdate = Tables['teachers']['Update']
export type TimetableSlotUpdate = Tables['timetable_slots']['Update']
export type TimetableUpdate = Tables['timetables']['Update']
export type NotificationUpdate = Tables['notifications']['Update']
