import { createAdminClient } from '@/lib/supabase/admin'
import { notFound } from 'next/navigation'

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const supabase = createAdminClient()

  const { data: link } = await supabase
    .from('share_links')
    .select(`
      *,
      sections(name, grades(name)),
      timetables(label, terms(name))
    `)
    .eq('token', token)
    .single()

  if (!link || new Date(link.expires_at) < new Date()) notFound()

  const { data: slots } = await supabase
    .from('timetable_slots')
    .select('*, subjects(*), teachers(name), rooms(name)')
    .eq('timetable_id', link.timetable_id)
    .eq('section_id', link.section_id)

  const { data: periodSlots } = await supabase
    .from('period_slots')
    .select('*')
    .eq('is_break', false)
    .order('slot_number')

  const section = link.sections as unknown as { name: string; grades: { name: string } | null }
  const timetable = link.timetables as unknown as { label: string; terms: { name: string } | null }
  const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']

  function getSlot(day: number, slotNumber: number) {
    return (slots ?? []).find((s) => s.day_of_week === day && s.slot_number === slotNumber)
  }

  return (
    <div className="min-h-screen bg-ivory px-6 py-10 max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-8 text-center">
        <div className="h-12 w-12 rounded-xl bg-mocha flex items-center justify-center mx-auto mb-4">
          <span className="text-ivory text-2xl font-bold font-cormorant">T</span>
        </div>
        <h1 className="font-cormorant text-3xl font-semibold text-espresso">
          {section.grades?.name} {section.name}
        </h1>
        <p className="text-taupe mt-1">{timetable.label} · {timetable.terms?.name}</p>
      </div>

      {/* Timetable grid */}
      <div className="overflow-x-auto">
        <table className="w-full border-separate border-spacing-1">
          <thead>
            <tr>
              <th className="w-20 text-xs text-taupe font-medium text-left pb-2">Period</th>
              {DAYS.map((d) => (
                <th key={d} className="text-xs text-taupe font-medium text-center pb-2">{d}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {(periodSlots ?? []).map((period) => (
              <tr key={period.slot_number}>
                <td className="align-top pr-2">
                  <p className="text-xs font-medium text-espresso">{period.label}</p>
                  <p className="text-[10px] text-taupe">{period.start_time?.slice(0, 5)}</p>
                </td>
                {DAYS.map((_, di) => {
                  const day = di + 1
                  const slot = getSlot(day, period.slot_number)
                  const subject = slot?.subjects as unknown as { name: string; color_hex: string } | null
                  const room = slot?.rooms as unknown as { name: string } | null
                  const teacher = slot?.teachers as unknown as { name: string } | null

                  return (
                    <td key={day} className="align-top">
                      {subject ? (
                        <div
                          className="h-20 rounded-lg px-2 py-1.5 border border-sand/40"
                          style={{
                            borderLeftColor: subject.color_hex,
                            borderLeftWidth: 3,
                            backgroundColor: `${subject.color_hex}26`,
                          }}
                        >
                          <p className="text-xs font-semibold text-espresso truncate leading-tight">
                            {subject.name}
                          </p>
                          {teacher && <p className="text-[10px] text-taupe mt-0.5 truncate">{teacher.name}</p>}
                          {room && <p className="text-[10px] text-taupe/70 truncate">{room.name}</p>}
                        </div>
                      ) : (
                        <div className="h-20 rounded-lg bg-cream/40 border border-sand/20" />
                      )}
                    </td>
                  )
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="text-center text-xs text-taupe/60 mt-8">
        Generated by Tablo · {new Date().toLocaleDateString()}
      </p>
    </div>
  )
}
